name: Compile application
run-name: ${{ github.actor }} is building application docker images
on: 
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Build server docker image
        run: docker build ./server --file ./server/dockerfile --tag server-image
      - name: Build client docker image
        run: docker build ./client --file ./client/dockerfile --tag client-image
